project:
  type: website
  render:
    - tp.qmd
website:
  title: "today"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true
