project:
  type: website
  render:
    - index.qmd
    - Courses/Bash/tp.qmd
    - Courses/CI/tp.qmd
    - Courses/Docs/tp.qmd
    - Courses/Git/tp.qmd
    - Courses/IDE/tp.qmd
    - Courses/Pandas/tp.qmd
    - Courses/Python-modules/tp.qmd
    - Courses/ScipyNumpy/tp.qmd
    - Courses/Test/tp.qmd
    - Courses/TimeMemory/tp.qmd
    - Courses/Venv/tp.qmd
    - Courses/ClassesExceptions/tp.qmd
website:
  title: "HAX712X: Software development for data sciences"
  site-url: https://josephsalmon.github.io/HAX712X/
  repo-url: https://github.com/josephsalmon/HAX712X
  page-navigation: true
  repo-actions: [edit, issue]
  sidebar:
    search: true
    contents:
      - section: "Courses"
        contents:
          - Courses/Bash/tp.qmd
          - Courses/CI/tp.qmd
          - Courses/Docs/tp.qmd
          - Courses/Git/tp.qmd
          - Courses/IDE/tp.qmd
          - Courses/Pandas/tp.qmd
          - Courses/Python-modules/tp.qmd
          - Courses/ScipyNumpy/tp.qmd
          - Courses/Test/tp.qmd
          - Courses/TimeMemory/tp.qmd
          - Courses/Venv/tp.qmd
          - Courses/ClassesExceptions/tp.qmd
      - section: "Bonus"

  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: HAX712X
format:
  html:
    theme:
      light: spacelab
    # mainfont: Atkinson Hyperlegible
    html-math-method: katex
    toc-location: right
    toc: true
    toc-depth: 6
    code-fold: false
    code-tools:
      toggle: false
      source: false
    # self-contained: true
    # page-layout: article
    code-overflow: wrap
    # fig-responsive: true
    # fig-format: svg
