project:
  type: website
  render:
    - /Courses/Bash/tp_Bash.qmd
    - index.qmd

website:
  title: "HAX712X: Software development for data sciences"
  sidebar:
    search: true
    contents:
      - section: "Courses"
        contents:
          - /Courses/Bash/tp_Bash.qmd
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: HAX712X
theme:
  light: spacelab
format:
  html:
    # mainfont: Atkinson Hyperlegible
    html-math-method: katex
    toc-location: left
    toc-depth: 6
    code-fold: false
    code-tools:
      toggle: false
      source: false
    # self-contained: true
    page-layout: article
    code-overflow: wrap
    # fig-responsive: true
    # fig-format: svg
